FROM oracle/database:11.2.0.2-xe
LABEL maintainer="yudaiogawa <19630931+yudaiogawa@users.noreply.github.com>"

COPY ./db/timezone-files/timezone_11.dat /u01/app/oracle/product/11.2.0/xe/oracore/zoneinfo/
COPY ./db/timezone-files/timezlrg_11.dat /u01/app/oracle/product/11.2.0/xe/oracore/zoneinfo/
