Vagrant.configure(2) do |config|

  # vagrant plugin install "vagrant-cachier"
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  # disable auto update of "Guest Addition"
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
    v.cpus = 1
    v.memory = 512
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.define :default do |machine|
    machine.vm.hostname = "default"
    machine.vm.network "private_network", ip: "192.168.33.10"
    machine.vm.synced_folder "./shared", "/usr/shere/nginx/html",
      :owner => "vagrant",
      :group => "vagrant",
      :mount_options => ["dmode=777,fmode=777"]
  end

  config.vm.provision "shell", path: "provision.sh"

end
